# Generated by Django 5.0.4 on 2024-07-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "Project_ID",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("Start_year", models.IntegerField(default=2019)),
                ("Acesss", models.TextField(default="Na")),
                ("Funding_Source", models.CharField(default="Unknown", max_length=100)),
                ("MetaData", models.TextField(default="No metadata available")),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
