# Generated by Django 5.0.4 on 2024-07-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Crop",
            field=models.CharField(
                choices=[
                    ("", "select"),
                    ("NA", "NA"),
                    ("Corn", "Corn"),
                    ("Cotton", "Cotton"),
                    ("Rice", "Rice"),
                    ("Fescue", "Fescue"),
                    ("Sorgum", "Sorgum"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="Project_Editors",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
