# Generated by Django 5.0.4 on 2024-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0003_experements_location_soil_profile_weather_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experements",
            name="harvest_date",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
