# Generated by Django 5.0.4 on 2024-07-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0007_rename_grids_id_location_fid_location_metadata"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table="project",
        ),
    ]
