# Generated by Django 5.0.4 on 2024-07-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0008_alter_project_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table="proj",
        ),
    ]
