# Generated by Django 5.0.4 on 2024-07-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0010_alter_experement_location_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experement",
            old_name="defoliation_1",
            new_name="defoliation_rate_1",
        ),
        migrations.RenameField(
            model_name="experement",
            old_name="defoliation_2",
            new_name="defoliation_rate_2",
        ),
        migrations.RenameField(
            model_name="experement",
            old_name="defoliation_3",
            new_name="defoliation_rate_3",
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_source_1",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_source_2",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_source_3",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_timing_1",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_timing_2",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_timing_3",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_unit_1",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_unit_2",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="defoliation_unit_3",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="n_unit_1",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="n_unit_2",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="n_unit_3",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="pix_unit_1",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="pix_unit_2",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experement",
            name="pix_unit_3",
            field=models.CharField(
                choices=[("u1", "u1"), ("u2", "u2"), ("u3", "u3")],
                default="NA",
                max_length=50,
            ),
        ),
    ]
