# Generated by Django 5.0.4 on 2024-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_twin",
            "0011_rename_defoliation_1_experement_defoliation_rate_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
