# Generated by Django 5.0.4 on 2024-07-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0013_alter_project_project_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table=None,
        ),
    ]
