# Generated by Django 5.0.4 on 2024-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0015_rename_project_id_project_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experement",
            old_name="experement_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="soil_profile",
            old_name="soil_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="weather",
            old_name="weather_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="forecasted_data_satellite",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="satellite_data",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="uav_data",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
