# Generated by Django 5.0.4 on 2024-07-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0016_rename_experement_id_experement_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table="my_custom_table_name",
        ),
    ]
