# Generated by Django 5.0.4 on 2024-07-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0018_alter_project_options_alter_project_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experement",
            options={"verbose_name_plural": "experement"},
        ),
        migrations.AlterModelOptions(
            name="forecasted_data_satellite",
            options={"verbose_name_plural": "forecasted_data_satellite"},
        ),
        migrations.AlterModelOptions(
            name="forecasted_data_uav",
            options={"verbose_name_plural": "forecasted_data_uav"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name_plural": "location"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name_plural": "project"},
        ),
        migrations.AlterModelOptions(
            name="satellite_data",
            options={"verbose_name_plural": "satellite_data"},
        ),
        migrations.AlterModelOptions(
            name="soil_profile",
            options={"verbose_name_plural": "soil_profile"},
        ),
        migrations.AlterModelOptions(
            name="uav_data",
            options={"verbose_name_plural": "uav_data"},
        ),
        migrations.AlterModelOptions(
            name="weather",
            options={"verbose_name_plural": "weather"},
        ),
    ]
