# Generated by Django 5.0.4 on 2024-07-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0019_alter_experement_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="county_id",
            new_name="county",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="state_id",
            new_name="state",
        ),
    ]
