# Generated by Django 5.0.4 on 2024-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0020_rename_county_id_location_county_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
