# Generated by Django 5.0.4 on 2024-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0023_alter_uav_data_d_10_1_alter_uav_data_d_10_10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
