# Generated by Django 5.0.4 on 2024-07-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_twin",
            "0027_alter_experement_planting_date_alter_experement_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
