# Generated by Django 5.0.4 on 2024-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0035_alter_uav_data_emergence_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="emergence_data",
            field=models.DateField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="forecasting_date",
            field=models.DateField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="pridicted_yield",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="satellite_data",
            name="emergence_data",
            field=models.DateField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="uav_data",
            name="Yield",
            field=models.FloatField(default=None, null=True),
        ),
    ]
