# Generated by Django 5.0.4 on 2024-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin", "0036_alter_forecasted_data_uav_emergence_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experement",
            name="defoliation_rate_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_rate_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_rate_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_source_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_source_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_source_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_timing_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_timing_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="defoliation_timing_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="harvest_date",
            field=models.DateField(default="Null"),
        ),
        migrations.AlterField(
            model_name="experement",
            name="metadata",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_rate_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_rate_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_rate_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_source_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_source_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_source_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_timing_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_timing_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="n_timing_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_rate_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_rate_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_rate_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_source_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_source_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_source_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_timing_1",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_timing_2",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="pix_timing_3",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="planting_date",
            field=models.DateField(default="Null"),
        ),
        migrations.AlterField(
            model_name="experement",
            name="satellite_raw",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="uav_dsm",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="uav_orthomosiac_MS",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="uav_orthomosiac_RGB",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="experement",
            name="uav_raw",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="forecasted_data_satellite",
            name="emergence_data",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="forecasted_data_satellite",
            name="feature",
            field=models.CharField(
                choices=[
                    ("", "select"),
                    ("NA", "NA"),
                    ("canopy_cover", "canopy_cover"),
                    ("canopy_height", "canopy_height"),
                    ("canopy_volume", "canopy_volume"),
                    ("exg", "exg"),
                    ("ndvi", "ndvi"),
                ],
                default="Null",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="forecasted_data_satellite",
            name="fid",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="forecasted_data_satellite",
            name="forecasting_date",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="forecasted_data_satellite",
            name="pridicted_yield",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="emergence_data",
            field=models.DateField(default="Null"),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="feature",
            field=models.CharField(
                choices=[
                    ("", "select"),
                    ("NA", "NA"),
                    ("canopy_cover", "canopy_cover"),
                    ("canopy_height", "canopy_height"),
                    ("canopy_volume", "canopy_volume"),
                    ("exg", "exg"),
                    ("ndvi", "ndvi"),
                ],
                default="Null",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="fid",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="forecasted_data_uav",
            name="forecasting_date",
            field=models.DateField(default="Null"),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="contact_info",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="county",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="fid",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="owner",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="plot_boundary",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="steet_address",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding_source",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="satellite_data",
            name="emergence_data",
            field=models.DateField(default="Null"),
        ),
        migrations.AlterField(
            model_name="satellite_data",
            name="feature",
            field=models.CharField(
                choices=[
                    ("", "select"),
                    ("NA", "NA"),
                    ("canopy_cover", "canopy_cover"),
                    ("canopy_height", "canopy_height"),
                    ("canopy_volume", "canopy_volume"),
                    ("exg", "exg"),
                    ("ndvi", "ndvi"),
                ],
                default="Null",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="satellite_data",
            name="fid",
            field=models.CharField(default="Null", max_length=100),
        ),
        migrations.AlterField(
            model_name="uav_data",
            name="emergence_data",
            field=models.DateField(default="Null"),
        ),
        migrations.AlterField(
            model_name="uav_data",
            name="feature",
            field=models.CharField(
                choices=[
                    ("", "select"),
                    ("NA", "NA"),
                    ("canopy_cover", "canopy_cover"),
                    ("canopy_height", "canopy_height"),
                    ("canopy_volume", "canopy_volume"),
                    ("exg", "exg"),
                    ("ndvi", "ndvi"),
                ],
                default="Null",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="uav_data",
            name="fid",
            field=models.CharField(default="Null", max_length=100),
        ),
    ]
